sudo: false
language: php
php:
- 5.6
- 7.0
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.composer/cache/files"
install:
- mv /home/travis/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ~/xdebug.ini
before_script:
- composer install --no-interaction --prefer-dist --no-progress --quiet
- mkdir -p build/docs
- mv ~/xdebug.ini /home/travis/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
script:
- phpunit --coverage-clover build/logs/clover.xml
- vendor/bin/phpdoc --quiet -d ./src -t ./build/docs
after_script:
- vendor/bin/test-reporter
after_success:
- bash .travis_after_success.sh
addons:
  code_climate:
   repo_token: "$CODECLIMATE_TOKEN"
  apt:
   packages:
   - graphviz
env:
  global:
  -secure: e/l+oD/q0H2vkI5i5w5aqNzpc2vDo3QBFTIdmAPzg4FkxOwNxqXceTa11JeLA/xeMHU4SRUrnZjS27YycnigtbZqsjFWufXajP6cpDc567Smeywj2ycA9FiM4zKB04cMStA99/XpzYyysBv0R1LSfubUjN0zDS7b42Is+Mlx91mVLbafLGd76MdYO9CXFZOi8cbzAb7U1Enkg4Lq0qXREQYnBnXj6qkgUw0aIxEfeuCck7xfZZR/CQbYTfzQHtwJcF6F4GRfrNuI9iNYUYST79p7xk2ZGPLGwhc+lAKyHzVxQYNWt9lHO4m3C5foIBoIfxNziwWOBEY3DB5Z0Q1LKgEQJjZIcIbcm2K1WgbQ33DF4uw+iUpICDWVuFO0VrISuff6h2EXsfTKtKn/4OKqXSp8EmcDxb1P+qqi3CRg74To+LEDWrlklBf4yzinIwRRFWHQilZlL81BTwKZwFAfzl05CuIsTX/Iu79lNt7RXSMSSDZMbYJNLghVy7RdMIKSnFa8AK4i95M9KAMQ8GOSlF1FivYkkAoT51Bs5VRzKkxQB0P6RITwaz272prfxJjEzWW/LXBK46IP7dM2REjkSUXcUoBnY8g8tK0Rlgz5ZrNHGg7MQpIiS9efe+iRxTpf6FoJdZbazVmIY5sl5B5Sv8vqE4KwCkMBBplKWgj8RmE=

